src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => "Electrique",
        1 => "Gaz",
    ];
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *     pattern="/^[0-9]{5}+$/",
     *     message="Code postal n'est pas validé"
     * )
     */
    private $codePostal;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTime;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function formatedPrice(): string
    {
        return number_format($this->price, 0, " ", " ");
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class,[
                'choices' => $this->getChoice(),
            ])
            ->add('city', null, [
                'label' => 'Ville'
            ])
            ->add('adress')
            ->add('codePostal')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }

    private function getChoice()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $key => $value){
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use ContainerG93yvNH\getResponseService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/biens", name="property_")
 */
class PropertyController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @param PropertyRepository $propertyRepository
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function index(PropertyRepository $propertyRepository, EntityManagerInterface $em): Response
    {
        return $this->render('property/index.html.twig', [
            'properties' => $propertyRepository->findAllVisible(),
        ]);
    }

    /**
     * @Route("/{id}", name="show")
     * @param Property $property
     * @return Response
     */
    public function show(Property $property): Response
    {
        return $this->render('property/show.html.twig',[
            'property' => $property
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Acheter{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Voir Tous Nos Biens </h1>
        {% for property in properties %}
            <ul>
                <li>{{ property.title }}
                    <ul>
                        <li>{{ property.title }}</li>
                        <li>{{ property.description }}</li>
                        <li>{{ property.surface }}</li>
                        <li>{{ property.rooms }}</li>
                        <li>{{ property.bedrooms }}</li>
                        <li>{{ property.floor }}</li>
                        <li>{{ property.price }}</li>
                        <li>{{ property.heat }}</li>
                        <li>{{ property.city }}</li>
                        <li>{{ property.adress }}</li>
                        <li>{{ property.codePostal }}</li>
                        <li>{{ property.sold }}</li>
                        <li>{{ property.createdAt|date('d/m/Y') }}</li>
                    </ul>
                </li>
            </ul>


        {% endfor %}
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title}}{% endblock %}

{% block body %}
    <div class="jumpbotron">
        <div class="row">
            <div class="col_md-8">
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces -{{ property.surface }} m2</h2>
                    <div class="text-primary" style="font-weight: bold;font-size: 2rem">{{property.formatedPrice}}€ </div>
                    <a href="#">Conacter l'agence</a>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
               <table class="table table-striped">
                   <tr>
                       <td>Surface habitable</td>
                       <td>{{ property.surface }}m2</td>
                   </tr>
                   <tr>
                       <td>Pièces</td>
                       <td>{{ property.rooms }}</td>
                   </tr>
                   <tr>
                       <td>Chambres</td>
                       <td>{{ property.bedrooms }}</td>
                   </tr>
                   <tr>
                       <td>Etage</td>
                       <td>{{ property.floor }}</td>
                   </tr>
                   <tr>
                       <td>Chauffage</td>
                       <td>{{ property.heatType }}</td>
                   </tr>
               </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>

            </div>
        </div>
    </div>

{% endblock %}